package uz.pdp.dreamexpressbot.entity.enums;

public enum TgState {

    START,
    ENTERING_PHONE_NUMBER,
    CHOOSING_MENU,
    SENDING_PHOTO,
    ENTERING_FIRST_NAME,
    CHOOSING_ORDER_MENU,
    CHOOSING_LANG,
    CHOOSING_SERVICE,
    GOING_BACK_TO_SERVICE_MENU,
    GOING_BACK_TO_MAIN_MENU,
    CHOOSING_CITY,
    SUBMITTING_ORDER,
    CHOOSING_PROFILE_MENU,
    CHANGING_FIRST_NAME,
    GOING_BACK_TO_PROFILE_MENU,
    CHANGING_PHONE_NUMBER,
    SELECTING_FAQ,
    GOING_BACK_TO_QUESTION_MENU, SENDING_LOCATION,

}
